import type { TSESLint } from '@typescript-eslint/utils';
import type { Config as ESLintCoreConfig, ConfigObject as ESLintCoreConfigObject } from 'eslint/config';

// Derived from a real library type rather than hand-written: a getter's return expression is only contextually typed against its own explicit return-type annotation, not against the outer object literal's type the way a plain property initializer would be -- without this, each rule's 'error' literal below would widen to plain `string`, which the real Config['rules'] shape rejects.
export type ConfigValue = NonNullable<TSESLint.FlatConfig.Plugin['configs']>[string];

// `ConfigValue` (a single named config's value type) is `Config | ConfigArray` -- a union that is NOT guaranteed to be an array, because a plugin's own `configs` map can also hand back a single flat config object. A value that is unconditionally an array needs `ConfigArrayValue` instead: annotating it with the full union directly was a real, confirmed bug -- `...recommendedTypeChecked` failed to typecheck with TS2488 ("must have a Symbol.iterator method") wherever a consumer spread it, since TypeScript can't prove a value typed as that union is iterable. `Extract<ConfigValue, unknown[]>` narrows to the array-only member of the same union.
export type ConfigArrayValue = Extract<ConfigValue, unknown[]>;

// The type this package's PUBLIC exports (exadevConfig's return type, defaultConfig) are declared as -- ESLint core's own Config (what both tseslint.config(...exadev) and ESLint 10's newer defineConfig(...exadev) actually accept as input), not @typescript-eslint/utils' TSESLint.FlatConfig.Config that ConfigArrayValue above uses internally while this package assembles its array (needed there for full rule-name/rule-options type-checking against typescript-eslint's own rule schemas). The two types describe the exact same real flat-config object at runtime, but TSESLint.FlatConfig.Config is not nominally assignable to @eslint/core's ConfigObject in this direction: TSESLint.FlatConfig.LanguageOptions is a concrete interface with no index signature, while @eslint/core's LanguageOptions is `Record<string, unknown>`. Confirmed reproducible with a bare, unmodified `tseslint.config(...)` array and zero involvement from this package's own code -- a genuine typescript-eslint/ESLint-core type gap, not a defect in the config objects this package builds. Confirmed the other direction too: an @eslint/core-typed array satisfies BOTH tseslint.config()'s own input type and defineConfig()'s, so re-typing the export at this one boundary (see exadevConfig's own cast) is what lets every consumer use either call without each needing its own copy of this same cast.
export type PublicConfigArray = ESLintCoreConfig[];

// Derived from ESLintCoreConfigObject's own `plugins` field (a real library type, not a hand-written interface), matching the derivation style ConfigValue above already uses. The named `plugin` export (this package's public entry point for a consumer wiring `plugins: { exadev: plugin }` straight into `defineConfig()`) needs @eslint/core's own Plugin shape for the same reason PublicConfigArray needs ESLintCoreConfig: `plugin`'s internal build (src/plugin.ts) is typed against @typescript-eslint/utils' TSESLint.FlatConfig.Plugin, whose `configs` field (`Record<string, TSESLint.FlatConfig.Config | TSESLint.FlatConfig.ConfigArray>`) is not assignable to @eslint/core's own `Record<string, LegacyConfigObject | ConfigObject | ConfigObject[]>` under `exactOptionalPropertyTypes: true` (confirmed directly: a bare `defineConfig({ plugins: { exadev: plugin } })` fails TS2375 on exactly this property before the cast in src/to-public-plugin.ts is applied). `@eslint/core` itself is deliberately not a direct import here, the same way PublicConfigArray avoids one for Config: indexing through `eslint/config`'s own re-exported `ConfigObject` keeps this package's peer surface at just `eslint`, which every consumer already has.
export type PublicPlugin = NonNullable<ESLintCoreConfigObject['plugins']>[string];

// @eslint/core's own Plugin.configs is a plain `Record<string, ...>` index signature, with no literal `recommended`/`barrel`/`react`/`nextjs` keys of its own, so PublicPlugin's own `configs` field is read the same way: index access, never dot access. That already held for the internal TSESLint.FlatConfig.Plugin type too (its own `configs` field, SharedConfigs, is likewise `{ [key: string]: Config | ConfigArray }`), so this is not a regression PublicPlugin introduces; a consumer wanting `plugin.configs.recommended` by name reads it as `plugin.configs?.recommended` cast through the internal `plugin` default export instead of the public one, or via `plugin.configs['recommended']`.
