import type { TSESLint } from '@typescript-eslint/utils';
import type { Config as ESLintCoreConfig } from 'eslint/config';

// Derived from a real library type rather than hand-written: a getter's return expression is only contextually typed against its own explicit return-type annotation, not against the outer object literal's type the way a plain property initializer would be -- without this, each rule's 'error' literal below would widen to plain `string`, which the real Config['rules'] shape rejects.
export type ConfigValue = NonNullable<TSESLint.FlatConfig.Plugin['configs']>[string];

// `ConfigValue` (a single named config's value type) is `Config | ConfigArray` -- a union that is NOT guaranteed to be an array, because a plugin's own `configs` map can also hand back a single flat config object. A value that is unconditionally an array needs `ConfigArrayValue` instead: annotating it with the full union directly was a real, confirmed bug -- `...recommendedTypeChecked` failed to typecheck with TS2488 ("must have a Symbol.iterator method") wherever a consumer spread it, since TypeScript can't prove a value typed as that union is iterable. `Extract<ConfigValue, unknown[]>` narrows to the array-only member of the same union.
export type ConfigArrayValue = Extract<ConfigValue, unknown[]>;

// The type this package's PUBLIC exports (exadevConfig's return type, defaultConfig) are declared as -- ESLint core's own Config (what both tseslint.config(...exadev) and ESLint 10's newer defineConfig(...exadev) actually accept as input), not @typescript-eslint/utils' TSESLint.FlatConfig.Config that ConfigArrayValue above uses internally while this package assembles its array (needed there for full rule-name/rule-options type-checking against typescript-eslint's own rule schemas). The two types describe the exact same real flat-config object at runtime, but TSESLint.FlatConfig.Config is not nominally assignable to @eslint/core's ConfigObject in this direction: TSESLint.FlatConfig.LanguageOptions is a concrete interface with no index signature, while @eslint/core's LanguageOptions is `Record<string, unknown>`. Confirmed reproducible with a bare, unmodified `tseslint.config(...)` array and zero involvement from this package's own code -- a genuine typescript-eslint/ESLint-core type gap, not a defect in the config objects this package builds. Confirmed the other direction too: an @eslint/core-typed array satisfies BOTH tseslint.config()'s own input type and defineConfig()'s, so re-typing the export at this one boundary (see exadevConfig's own cast) is what lets every consumer use either call without each needing its own copy of this same cast.
export type PublicConfigArray = ESLintCoreConfig[];
