import type { TSESLint } from '@typescript-eslint/utils';

import type { Config as ESLintCoreConfig, ConfigObject as ESLintCoreConfigObject } from 'eslint/config';

/**
 * Derived from a real library type rather than hand-written: a getter's return expression is only contextually typed against its own explicit return-type annotation, not against the outer object literal's type the way a plain property initializer would be -- without this, each rule's 'error' literal below would widen to plain `string`, which the real Config['rules'] shape rejects.
 */
export type ConfigValue = NonNullable<TSESLint.FlatConfig.Plugin['configs']>[string];

// `ConfigValue` (a single named config's value type) is `Config | ConfigArray` -- a union that is NOT guaranteed to be an array, because a plugin's own `configs` map can also hand back a single flat config object. A value that is unconditionally an array needs `ConfigArrayValue` instead: annotating it with the full union directly was a real, confirmed bug -- `...recommendedTypeChecked` failed to typecheck with TS2488 ("must have a Symbol.iterator method") wherever a consumer spread it, since TypeScript can't prove a value typed as that union is iterable. `Extract<ConfigValue, unknown[]>` narrows to the array-only member of the same union.
export type ConfigArrayValue = Extract<ConfigValue, unknown[]>;

// The type this package's PUBLIC exports (exadevConfig's return type, defaultConfig) are declared as -- ESLint core's own Config (what both tseslint.config(...exadev) and ESLint 10's newer defineConfig(...exadev) actually accept as input), not @typescript-eslint/utils' TSESLint.FlatConfig.Config that ConfigArrayValue above uses internally while this package assembles its array (needed there for full rule-name/rule-options type-checking against typescript-eslint's own rule schemas). The two types describe the exact same real flat-config object at runtime, but TSESLint.FlatConfig.Config is not nominally assignable to @eslint/core's ConfigObject in this direction: TSESLint.FlatConfig.LanguageOptions is a concrete interface with no index signature, while @eslint/core's LanguageOptions is `Record<string, unknown>`. Confirmed reproducible with a bare, unmodified `tseslint.config(...)` array and zero involvement from this package's own code -- a genuine typescript-eslint/ESLint-core type gap, not a defect in the config objects this package builds. Confirmed the other direction too: an @eslint/core-typed array satisfies BOTH tseslint.config()'s own input type and defineConfig()'s, so re-typing the export at this one boundary (see exadevConfig's own cast) is what lets every consumer use either call without each needing its own copy of this same cast.
export type PublicConfigArray = ESLintCoreConfig[];

// What each of PublicPlugin's four bundled configs actually resolves to at runtime (src/plugin.ts's own getters): `recommended`/`barrel` are each a single flat config object; `react`/`nextjs` are each an array, since building React/Next.js support composes more than one upstream config block (src/react.ts/src/nextjs.ts). Never a LegacyConfigObject: @eslint/core's own Plugin['configs'] allows one, but none of the four getters ever return one, so the public type doesn't need to describe one either.
export type PublicConfigObject = ESLintCoreConfigObject | ESLintCoreConfigObject[];

/* Derived from ESLintCoreConfigObject's own `plugins` field (a real library type, not a hand-written interface), matching the derivation style ConfigValue above already uses. The named `plugin` export (this package's public entry point for a consumer wiring `plugins: { exadev: plugin }` straight into `defineConfig()`) needs @eslint/core's own Plugin shape for the same reason PublicConfigArray needs ESLintCoreConfig: `plugin`'s internal build (src/plugin.ts) is typed against @typescript-eslint/utils' TSESLint.FlatConfig.Plugin, whose `configs` field (`Record<string, TSESLint.FlatConfig.Config | TSESLint.FlatConfig.ConfigArray>`) is not assignable to @eslint/core's own `Record<string, LegacyConfigObject | ConfigObject | ConfigObject[]>` under `exactOptionalPropertyTypes: true` (confirmed directly: a bare `defineConfig({ plugins: { exadev: plugin } })` fails TS2375 on exactly this property before the cast in src/to-public-plugin.ts is applied). `@eslint/core` itself is deliberately not a direct import here, the same way PublicConfigArray avoids one for Config: indexing through `eslint/config`'s own re-exported `ConfigObject` keeps this package's peer surface at just `eslint`, which every consumer already has.

   PublicPlugin further narrows Plugin's own `configs` field down to the shape README.md actually documents: exactly the four literal keys src/plugin.ts's own object declares, each typed as PublicConfigObject above, in place of Plugin's own `configs?: Record<string, LegacyConfigObject | ConfigObject | ConfigObject[]> | undefined`. Without this narrowing, `plugin.configs.recommended` fails three ways at once under a plain `strict: true` consumer tsconfig plus this repo's own `noPropertyAccessFromIndexSignature`: TS4111 (Plugin['configs'] has no literal keys, only an index signature, so dot access is rejected), TS18048 even after switching to index access (`configs` itself is optional on the un-narrowed type), and TS2322 wherever the result is then used as an `extends` element (LegacyConfigObject's own `plugins` field is `string[]`, not the `Record<string, Plugin>` an `ExtendsElement`/`InfiniteArray<ConfigWithExtends>` requires): confirmed directly against `tseslint.config({ extends: [plugin.configs.recommended] })` and the equivalent `defineConfig()` React/Next.js examples (README.md's own "lighter option" and "Optional features" sections; see src/readme-examples.ts). */
export type PublicPlugin = Omit<NonNullable<ESLintCoreConfigObject['plugins']>[string], 'configs'> & {
  readonly configs: Readonly<Record<'recommended' | 'barrel' | 'react' | 'nextjs', PublicConfigObject>>;
};
