import stylistic from '@stylistic/eslint-plugin';
import type { ConfigArrayValue } from './config-types';
import { JSX_FILE_PATTERNS } from './react';
import plugin from './plugin';

/* @stylistic/eslint-plugin (the unified successor to the split @stylistic/eslint-plugin-js/-ts/-jsx packages) is bundled unconditionally here, the same way jsdoc.ts and json-canonical.ts are: it is a plain dependency of this package (see package.json), so every consumer already has it the moment they depend on this package at all, and every rule wired below matches purely on comment/statement/JSX shape, never on formatting (indentation, quotes, semicolons, trailing commas, line wrapping, bracket spacing), which stays Prettier's job in every consumer of this package. Only a hand-picked subset of the plugin's own rules is enabled below (never a spread `stylistic.configs.recommended`/`.all`), mirroring jsdoc.ts's own plain-rules-object precedent: most of this plugin's own surface (indent, quotes, semi, comma-dangle, and the rest) genuinely is Prettier's job and would fight it directly, and eslint-config-prettier's own disabled-rules list (github.com/prettier/eslint-config-prettier, `index.js`) was checked directly against every rule id enabled below to confirm none of them appears there: each one enabled here is a rule Prettier has no opinion on at all (comment shape/position, blank-line placement between statements/class members, JSX prop-value conventions), not a formatting rule Prettier already owns.
   
   Every rule/option pair below was verified directly against the installed package's own rule source under node_modules/@stylistic/eslint-plugin/dist/rules/ (schema, defaultOptions, and fixer behaviour), not assumed from memory or a docs summary. See each rule's own comment for what that inspection found. `curly-newline`, `jsx-function-call-newline`, `jsx-props-style` and `list-style` are all deliberately not enabled: each governs line breaks and wrapping inside brackets, argument lists and JSX props, which is layout Prettier already owns, so enabling it would fight Prettier in every consumer. (`list-style` graduated from its experimental `exp-list-style` id in 6.0.0, per the plugin's own upgrade guide, https://eslint.style/guide/upgrade.)
   
   JSX's shorthand-boolean-prop convention (`<Foo enabled />` vs `<Foo enabled={true} />`) and shorthand-fragment syntax (`<>...</>` vs `<React.Fragment>...</React.Fragment>`) have their own rules in @stylistic/eslint-plugin since 6.0.0-beta.5, `jsx-shorthand-boolean` and `jsx-shorthand-fragment` (confirmed against the installed package's dist/rules/), but neither is enabled here, and neither is `eslint-plugin-react`'s own equivalent pair (`react/jsx-boolean-value`, `react/jsx-fragments`) in `src/react.ts`: adopting either convention is a separate decision from the comment and statement rules this file exists for.
   
   `multiline-comment-style` is enabled at `'bare-block'` through this package's own `exadev/multiline-comment-style` (src/rules/multiline-comment-style.ts), never as `@stylistic/multiline-comment-style`, which stays unconfigured. The installed 6.0.0-beta.6 carries the fix from https://github.com/eslint-stylistic/eslint-stylistic/pull/1251 (for issue https://github.com/eslint-stylistic/eslint-stylistic/issues/1249): the rule drops every comment its own `isDirectiveComment` matches before grouping a `//` run, so `prettier-ignore`, `c8 ignore`/`v8 ignore`, `istanbul ignore`, `node:coverage`, webpack magic comments, `@ts-expect-error`/`@ts-ignore`/`@ts-nocheck`/`@ts-check` and triple-slash reference/AMD directives all stay standalone `//` lines, and two consecutive `/// <reference ... />` lines are never merged either (the case https://github.com/eslint-stylistic/eslint-stylistic/issues/1285 reports, open upstream but no longer reproducible against this release). `TODO`/`FIXME`, `cspell:*`, `biome-ignore` and `#region`/`#endregion` are not in that list (`COMMENT_DIRECTIVE_PATTERNS` in the installed dist/utils.js), and the rule has no option to extend it; https://github.com/eslint-stylistic/eslint-stylistic/issues/1287 asks upstream to add `TODO`/`FIXME`. Folding one is not cosmetic: `exadev/prefer-doc-comment` treats such a line in a `//` run as a boundary and converts only the prose below it into the declaration's doc comment, but once the stylistic fixer has merged the whole run into one bare block it leaves that block alone, so an exported declaration silently loses its doc comment and nothing is reported. The wrapper runs the upstream rule unchanged except that every comment `exadev/prefer-doc-comment` treats as a directive is hidden from its grouping, so such a line breaks the run exactly as an upstream directive does. The upstream bare-block fixer still hard-codes a `\n` line break inside the replacement text it generates, whatever the file's own line endings, so a CRLF file gets mixed line endings inside a merged block; the wrapper does not change that (pinned by this file's tests). */
const JS_TS_FILE_PATTERNS = '**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}';

const stylisticCommentsConfig: ConfigArrayValue = [
  {
    files: [JS_TS_FILE_PATTERNS],
    plugins: { '@stylistic': stylistic, exadev: plugin },
    rules: {
      // `'always'` (the default), requiring a space after `//`/`/*`, with an added `block.markers: ['!']` on top of the bare default. Verified directly against the rule's own source that the bare default does not fight eslint-plugin-jsdoc/tsdoc: its default `markers` list always includes `'*'` (`parseMarkersOption` unconditionally appends it), so a `/**`-opening doc block is itself treated as an allowed "marker" comment and only ever needs a space/newline after that leading `*`, never additionally after the `/*`, exactly what a real `/** @remarks ... */`-style TSDoc block already looks like. A shebang line is exempted unconditionally by the rule's own `Program` handler. The bare default has no `'!'` marker of its own: `parseMarkersOption` never adds one the way it adds `'*'`, so EVERY `/*!` license/banner block (the shape prefer-doc-comment.ts's own checkAnchor also exempts, see that file's own header comment) failed this rule at its bare default, reported as "Expected space or tab after /*", confirmed directly against a properly spaced `/*! Copyright */` and a multi-line `/*!\n * Banner\n */` alike, both still reported: the rule reads only the single character right after the delimiter, finds `!`, and, since `!` is neither whitespace nor a recognised marker at the bare default, reports it regardless of whatever follows. Adding `'!'` to `block.markers` (verified directly against the rule's own `createAlwaysStylePattern`) does not remove the space requirement, it relocates it: the marker itself is now accepted immediately after the delimiter, but a space or newline is still mandatory immediately after THAT marker, so a spaced `/*! Copyright */` now passes while an unspaced `/*!Copyright*/` still fails, reported as "Expected space or tab after /*!" and fixed by inserting the missing space right after the `!`. This closes the banner gap without touching `line.markers`, since a `//!` banner is not a shape either sibling rule recognises or this package has any reason to invent support for.
      //
      // A triple-slash reference/AMD directive is exempted in both its spaced and its no-space form: `checkCommentForSpace` returns early for any comment `isTripleSlashReference` matches, whose pattern (`/^\/\s*<(?:reference|amd-)/u` in the installed dist/utils.js, matched against a `//`-stripped `///` comment's `.value`, which starts with the lone leftover third slash) allows optional whitespace after that slash, the same latitude TypeScript's own `fullTripleSlashReferencePathRegEx` gives. So `/// <reference types="..." />`, TypeScript's compiler-emitted spelling, and `///<reference types="..." />` are both left untouched. Before 6.0.0 the exemption was a hard-coded `startsWith('/ <reference')`, so the no-space form was reported and `--fix` rewrote it into `// /<reference types="..." />`, which TypeScript no longer parses as a directive (https://github.com/ExaDev/eslint-config/issues/47); this file's tests pin both forms.
      //
      // `line.markers: ['#', '#region', '#endregion']`, confirmed directly against a `Linter#verifyAndFix` probe: the bare default (no `line.markers` at all) also breaks a source-map comment, rewriting `//# sourceMappingURL=a.js.map`/`//# sourceURL=a.js` into `// # sourceMappingURL=...`/`// # sourceURL=...`, which browsers and Node no longer recognise as the directive it is. A bare `line: { markers: ['#'] }` fixes those two but breaks the OTHER `#`-prefixed convention this file's own rules already recognise, an editor `//#region`/`//#endregion` fold marker (see prefer-doc-comment.ts's own OTHER_DIRECTIVE_PATTERN): it turns `//#region` into `//# region`, which VS Code's own folding regex no longer matches. Listing `'#region'`/`'#endregion'` as markers too, alongside the bare `'#'`, closes both gaps at once: each of the four shapes (`//# sourceMappingURL=...`, `//# sourceURL=...`, `//#region`, `//#endregion`) is recognised as its own marker and left completely untouched, confirmed directly against all four. An already-spaced `// #region`/`// #endregion` needs no marker at all either way, since it already has its own space after `//`.
      '@stylistic/spaced-comment': ['error', 'always', { block: { markers: ['!'] }, line: { markers: ['#', '#region', '#endregion'] } }],
      // Bare default options (`'always'`, `{ exceptAfterOverload: true, exceptAfterSingleLine: false }`). This repository's own source has no class declarations outside test fixtures to check against a real fixture, so a small one was traced through the rule's own source instead: it fires once per adjacent pair of class members lacking (or having, under `'never'`) a blank line between them, is unconditionally fixable (`fixable: 'whitespace'`), and the `exceptAfterOverload` default specifically means a run of `.d.ts`-style TS method-overload signatures (each an empty-bodied `TSAbstractMethodDefinition`/`MethodDefinition`) is exempt from the blank-line requirement between each other, the shape that would otherwise be the most likely to genuinely conflict with hand-written overload blocks.
      '@stylistic/lines-between-class-members': 'error',
      // 'above': this project wants a `//` comment positioned above the code it describes, never trailing beside it on the same line. Verified directly against the rule's own source that this has no autofix at all (no `fixable` key in its `meta`, confirmed by inspecting the installed rule module directly, not assumed from its name alongside every other rule here that is `fixable`), and that, at its default `applyDefaultIgnorePatterns: true`, it already exempts every comment the plugin's shared `isDirectiveComment` matches (the `eslint`/`jshint`/`istanbul`/`@ts-*`/`prettier-ignore`/`c8`/`v8`/`node:coverage`/webpack family and triple-slash references) plus a dedicated `falls?\s?through` exemption for a switch-case fallthrough comment, so a same-line `// eslint-disable-line ...`/`// falls through` is never force-relocated above its statement. The one further directive that genuinely MUST trail is exempted by hand via `ignorePattern` (an option of the installed rule, read directly off its own source, matched against the comment's raw value): `cspell:disable-line` suppresses spell-checking for the very line it sits on, so honouring the report and moving it above (by hand, since there is no autofix) silently retargets the suppression at the previous line instead, disabling nothing the author intended; prefer-doc-comment.ts's own OTHER_DIRECTIVE_PATTERN already recognises it as a live directive and never folds it into a doc comment, whatever its position. Every other directive this package recognises applies to the line(s) BELOW it (`cspell:disable-next-line`, `@ts-expect-error`, `prettier-ignore`, `c8 ignore next`, `biome-ignore`, ...), so 'above' relocates those correctly and none needs an exemption of its own. The pattern is anchored and word-bounded (`^\s*cspell:disable-line\b`, tolerating exactly the leading whitespace a real directive comment carries after its `//`) so it matches a directive line and nothing else: `cspell:disable-liner`-shaped prose is still reported, and an ordinary trailing comment never matching the prefix stays reported too.
      '@stylistic/line-comment-position': ['error', { position: 'above', ignorePattern: '^\\s*cspell:disable-line\\b' }],
      // Five entries: the first, second and last enforce a blank line after a directive prologue, after an import block, and before a `return`; the middle two close a real gap those three leave on their own. `getPaddingType` scans the options array from its LAST entry backward and returns the first match (verified directly against the rule's own source), so a later array entry outranks an earlier one whenever both match the same pair, not merely on a tie. `'directive'`/`next: '*'` and `['cjs-import', 'import']`/`next: '*'` each match a directive-to-directive or import-to-import pair too, since `'*'` matches anything, so on their own they demand a blank line after EVERY directive and EVERY import, not only after the last one in a run: confirmed directly by running the installed rule against a fixture of two directives followed by two imports followed by a `require`, which came back with a blank line forced between every single one of those five lines. The two `blankLine: 'any'` entries below sit after both `'*'`-matching entries specifically so they win that same backward scan for a directive-to-directive or import-to-import pair, restoring "no opinion either way" there while leaving the original entries' own `next: '*'` (a directive/import followed by anything else, including the FIRST non-directive/non-import statement) untouched. `'directive'` matches a top-of-scope prologue (`"use strict"` and the like); `['cjs-import', 'import']` matches either a `const x = require('y')` CommonJS-style import or a real ESM `import` statement; `'return'` matches any `return` statement.
      '@stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: ['cjs-import', 'import'], next: '*' },
        { blankLine: 'any', prev: 'directive', next: 'directive' },
        { blankLine: 'any', prev: ['cjs-import', 'import'], next: ['cjs-import', 'import'] },
        { blankLine: 'always', prev: '*', next: 'return' },
      ],
      // This package's own bespoke doc-comment-upgrade rule. See src/rules/prefer-doc-comment.ts for its full design. Wired here, alongside the stylistic-plugin rules above, rather than in plugin.ts's own `recommended`/`barrel` configs, since it belongs to this same "comment discipline" bundle and is unconditional for every consumer exactly like jsdoc.ts/json-canonical.ts, not an opt-in tier a consumer selects piecemeal.
      // `'bare-block'`: a run of `//` lines becomes one `/* ... */` block with no leading `*` on its middle lines, the shape `exadev/prefer-doc-comment` then upgrades to a doc comment where the run documents an exported declaration. See this file's header comment for why it is this package's wrapper rather than the plugin's own id.
      'exadev/multiline-comment-style': ['error', 'bare-block'],
      'exadev/prefer-doc-comment': 'error',
    },
  },
  {
    // Scoped to real JSX files only, the identical justification react.ts's own JSX_FILE_PATTERNS block already uses: even though none of these three rules has any dependency (direct or peer) on eslint-plugin-react or React itself (confirmed directly against @stylistic/eslint-plugin's own package.json, whose `peerDependencies` are `eslint` and `oxlint`, both optional), each one's own AST selector only ever matches a JSXElement/JSXOpeningElement/JSXFragment node, so it is a structural no-op on every non-JSX file regardless of scoping. The `files` scoping here exists only to avoid ESLint computing rule state against a merged config for a file the rule set could never fire on, matching this same file's own JS_TS_FILE_PATTERNS block one step further.
    files: [...JSX_FILE_PATTERNS],
    plugins: { '@stylistic': stylistic },
    rules: {
      // Bare default options (`{ props: 'never', children: 'never', propElementValues: 'ignore' }`). Bans a redundant `{'literal text'}` JSX curly-brace wrapper around a prop value or child that could just as well be plain text/a plain attribute string, a real, autofixable anti-pattern Prettier has no opinion on at all (Prettier reformats whatever curly-brace-or-not shape it's handed; it never adds or removes the braces themselves).
      '@stylistic/jsx-curly-brace-presence': 'error',
      // Bare default options (`{ allowAllCaps: false, allowLeadingUnderscore: false, allowNamespace: false }`). Verified directly against the rule's own source (`isDOMComponent`, checked first and unconditionally) that a lowercase-initial tag such as `<myComp />` is never examined at all: JSX itself already reads that as an intrinsic HTML element, not a user component, so this rule only ever runs its own check against a name JSX already treats as a component (one starting with a capital letter, or dotted/namespaced). What it then enforces on that name is genuine PascalCase, catching a stray underscore or other non-alphanumeric character partway through it (`<My_component />`), not the initial letter's own case.
      '@stylistic/jsx-pascal-case': 'error',
      // Bare default options (`{ component: true, html: true }`). Requires `<Foo />` over `<Foo></Foo>` for both a user component and a plain HTML element with no children, a real content/shape choice (not a whitespace/formatting one) Prettier leaves entirely alone.
      '@stylistic/jsx-self-closing-comp': 'error',
    },
  },
];

export default stylisticCommentsConfig;
