import stylistic from '@stylistic/eslint-plugin';
import type { ConfigArrayValue } from './config-types';
import { JSX_FILE_PATTERNS } from './react';
import plugin from './plugin';

/* @stylistic/eslint-plugin (the unified successor to the split @stylistic/eslint-plugin-js/-ts/-jsx packages) is bundled unconditionally here, the same way jsdoc.ts and json-canonical.ts are: it is a plain dependency of this package (see package.json), so every consumer already has it the moment they depend on this package at all, and every rule wired below matches purely on comment/statement/JSX shape, never on formatting (indentation, quotes, semicolons, trailing commas, line wrapping, bracket spacing), which stays Prettier's job in every consumer of this package. Only a hand-picked subset of the plugin's own rules is enabled below (never a spread `stylistic.configs.recommended`/`.all`), mirroring jsdoc.ts's own plain-rules-object precedent: most of this plugin's own surface (indent, quotes, semi, comma-dangle, and the rest) genuinely is Prettier's job and would fight it directly, and eslint-config-prettier's own disabled-rules list (github.com/prettier/eslint-config-prettier, `index.js`) was checked directly against every rule id enabled below to confirm none of them appears there: each one enabled here is a rule Prettier has no opinion on at all (comment shape/position, blank-line placement between statements/class members, JSX prop-value conventions), not a formatting rule Prettier already owns.

   Every rule/option pair below was verified directly against the installed package's own rule source under node_modules/@stylistic/eslint-plugin/dist/rules/ (schema, defaultOptions, and fixer behaviour), not assumed from memory or a docs summary. See each rule's own comment for what that inspection found. `curly-newline`, `jsx-function-call-newline`, `exp-jsx-props-style` (the actual installed id behind the task's "jsx-props-style"), and `exp-list-style` (behind "list-style") are all deliberately not enabled: each is narrow/obscure enough (an `exp-` prefix in this plugin's own rule ids denotes an experimental rule, still finding its final shape) that it isn't worth this package's own consumers picking up unasked.

   A rule genuinely covering JSX's shorthand-boolean-prop convention (`<Foo enabled />` vs `<Foo enabled={true} />`) or shorthand-fragment syntax (`<>...</>` vs `<React.Fragment>...</React.Fragment>`) does not exist anywhere in @stylistic/eslint-plugin, confirmed directly against the installed package's full `Object.keys(rules)` list (none matching `boolean`/`fragment` in id or, checked via the built dist source, in description either). Those two conventions are instead `eslint-plugin-react`'s own `react/jsx-boolean-value` and `react/jsx-fragments`, an entirely different package this file does not touch. `src/react.ts`'s own optional-peer-dependency gate is the correct, and only, place either could ever be added, and doing so is explicitly out of scope for this change.

   `multiline-comment-style` (`'bare-block'`) is deliberately NOT enabled at all, despite being the one rule the task originally commissioning this bundle asked for by name: the installed v5.10.0's own comment-grouping filter, `COMMENTS_IGNORE_PATTERN`, only recognises `eslint`/`jshint`/`jslint`/`istanbul`/`global(s)`/`exported`/`jscs`-prefixed comments as directives, so a `// prettier-ignore`, `// c8 ignore ...`/`// v8 ignore ...`, `// @ts-expect-error`/`// @ts-ignore`/`// @ts-nocheck`/`// @ts-check`, or `// TODO`/`// FIXME` comment sitting in a run with ordinary prose gets folded into the run's own bare block, destroying it as a directive (confirmed directly by running the installed rule against each shape). A lost `prettier-ignore` in particular lets Prettier reformat the exact code the directive existed to protect. The rule also merges two or more consecutive triple-slash reference/AMD directives into one broken block regardless of file extension (every ambient `.d.ts` TypeScript itself generates, and a `vite.config.ts` following Vitest's own documented `/// <reference types="vitest" />` convention, both break this way), and its own bare-block fixer hard-codes a `\n` line break inside the replacement text it generates regardless of the file's own real convention, corrupting a CRLF file. This is a real, upstream-confirmed defect, not a documentation gap: eslint-stylistic's own issue https://github.com/eslint-stylistic/eslint-stylistic/issues/1249 names exactly the directive-swallowing failure, fixed by the merged https://github.com/eslint-stylistic/eslint-stylistic/pull/1251 (which folds `prettier-ignore`/`c8`/`v8`/`node:coverage`/webpack magic comments/`@ts-*` and the triple-slash case into one shared `isDirectiveComment` check reused by `multiline-comment-style` itself), and the standalone triple-slash gap is also tracked at this package's own filed https://github.com/eslint-stylistic/eslint-stylistic/issues/1285. Neither fix has reached a stable release yet: the latest stable @stylistic/eslint-plugin remains 5.10.0, and PR #1251 only exists in the `6.0.0-beta.6` prerelease, not a version this shared, published config can respectably pin its own consumers to. Re-enable `multiline-comment-style` once a stable release contains PR #1251's fix; until then, `exadev/prefer-doc-comment` alone still upgrades a substantial leading comment into a proper doc comment (see src/rules/prefer-doc-comment.ts), it simply never also merges a bare `//` run into a block comment of its own. */
const JS_TS_FILE_PATTERNS = '**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}';

const stylisticCommentsConfig: ConfigArrayValue = [
  {
    files: [JS_TS_FILE_PATTERNS],
    plugins: { '@stylistic': stylistic, exadev: plugin },
    rules: {
      // `'always'` (the default), requiring a space after `//`/`/*`, with an added `block.markers: ['!']` on top of the bare default. Verified directly against the rule's own source that the bare default does not fight eslint-plugin-jsdoc/tsdoc: its default `markers` list always includes `'*'` (`parseMarkersOption` unconditionally appends it), so a `/**`-opening doc block is itself treated as an allowed "marker" comment and only ever needs a space/newline after that leading `*`, never additionally after the `/*`, exactly what a real `/** @remarks ... */`-style TSDoc block already looks like. Triple-slash reference/AMD directives (`node.value.startsWith('/ <reference'` / `'/ <amd'`, since a `//`-stripped `///` comment's own `.value` starts with a lone leftover `/`) and shebang lines are both explicitly exempted in the rule's own `checkCommentForSpace`/`Program` handlers, so neither is broken by this rule either. The bare default, though, has no `'!'` marker of its own: `parseMarkersOption` never adds one the way it adds `'*'`, so a `/*!` license/banner block (the shape prefer-doc-comment.ts's own checkAnchor also exempts, see that file's own header comment) failed this rule at its bare default, reported as "Expected space or tab after /*" the moment the `!` sat directly against the exclamation with no space of its own before the banner's real text. Adding `'!'` to `block.markers` (verified directly against the rule's own `createAlwaysStylePattern`: a listed marker is accepted immediately after the delimiter, in place of, not in addition to, the mandatory following space) closes that gap without touching `line.markers`, since a `//!` banner is not a shape either sibling rule recognises or this package has any reason to invent support for.
      '@stylistic/spaced-comment': ['error', 'always', { block: { markers: ['!'] } }],
      // Bare default options (`'always'`, `{ exceptAfterOverload: true, exceptAfterSingleLine: false }`). This repository's own source has no class declarations outside test fixtures to check against a real fixture, so a small one was traced through the rule's own source instead: it fires once per adjacent pair of class members lacking (or having, under `'never'`) a blank line between them, is unconditionally fixable (`fixable: 'whitespace'`), and the `exceptAfterOverload` default specifically means a run of `.d.ts`-style TS method-overload signatures (each an empty-bodied `TSAbstractMethodDefinition`/`MethodDefinition`) is exempt from the blank-line requirement between each other, the shape that would otherwise be the most likely to genuinely conflict with hand-written overload blocks.
      '@stylistic/lines-between-class-members': 'error',
      // 'above': this project wants a `//` comment positioned above the code it describes, never trailing beside it on the same line. Verified directly against the rule's own source that this has no autofix at all (no `fixable` key in its `meta`, confirmed by inspecting the installed rule module directly, not assumed from its name alongside every other rule here that is `fixable`), and that it already exempts the same `eslint`/`jshint`/`istanbul`/... directive-comment family `spaced-comment`'s default `markers` shares (via the identical `COMMENTS_IGNORE_PATTERN`) plus a dedicated `falls?\s?through` exemption for a switch-case fallthrough comment, so a same-line `// eslint-disable-line ...`/`// falls through` is never force-relocated above its statement.
      '@stylistic/line-comment-position': ['error', 'above'],
      // The task's own three entries, plus two more closing a real gap they left: `getPaddingType` scans the options array from its LAST entry backward and returns the first match (verified directly against the rule's own source), so a later array entry outranks an earlier one whenever both match the same pair, not merely on a tie. `'directive'`/`next: '*'` and `['cjs-import', 'import']`/`next: '*'` each match a directive-to-directive or import-to-import pair too, since `'*'` matches anything, so on their own they demand a blank line after EVERY directive and EVERY import, not only after the last one in a run: confirmed directly by running the installed rule against a fixture of two directives followed by two imports followed by a `require`, which came back with a blank line forced between every single one of those five lines. The two `blankLine: 'any'` entries below sit after both `'*'`-matching entries specifically so they win that same backward scan for a directive-to-directive or import-to-import pair, restoring "no opinion either way" there while leaving the original entries' own `next: '*'` (a directive/import followed by anything else, including the FIRST non-directive/non-import statement) untouched. `'directive'` matches a top-of-scope prologue (`"use strict"` and the like); `['cjs-import', 'import']` matches either a `const x = require('y')` CommonJS-style import or a real ESM `import` statement; `'return'` matches any `return` statement.
      '@stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: ['cjs-import', 'import'], next: '*' },
        { blankLine: 'any', prev: 'directive', next: 'directive' },
        { blankLine: 'any', prev: ['cjs-import', 'import'], next: ['cjs-import', 'import'] },
        { blankLine: 'always', prev: '*', next: 'return' },
      ],
      // This package's own bespoke doc-comment-upgrade rule. See src/rules/prefer-doc-comment.ts for its full design. Wired here, alongside the stylistic-plugin rules above, rather than in plugin.ts's own `recommended`/`barrel` configs, since it belongs to this same "comment discipline" bundle and is unconditional for every consumer exactly like jsdoc.ts/json-canonical.ts, not an opt-in tier a consumer selects piecemeal.
      'exadev/prefer-doc-comment': 'error',
    },
  },
  {
    // Scoped to real JSX files only, the identical justification react.ts's own JSX_FILE_PATTERNS block already uses: even though none of these three rules has any dependency (direct or peer) on eslint-plugin-react or React itself (confirmed directly against @stylistic/eslint-plugin's own package.json, whose only `peerDependencies` entry is `eslint` itself), each one's own AST selector only ever matches a JSXElement/JSXOpeningElement/JSXFragment node, so it is a structural no-op on every non-JSX file regardless of scoping. The `files` scoping here exists only to avoid ESLint computing rule state against a merged config for a file the rule set could never fire on, matching this same file's own JS_TS_FILE_PATTERNS block one step further.
    files: [...JSX_FILE_PATTERNS],
    plugins: { '@stylistic': stylistic },
    rules: {
      // Bare default options (`{ props: 'never', children: 'never', propElementValues: 'ignore' }`). Bans a redundant `{'literal text'}` JSX curly-brace wrapper around a prop value or child that could just as well be plain text/a plain attribute string, a real, autofixable anti-pattern Prettier has no opinion on at all (Prettier reformats whatever curly-brace-or-not shape it's handed; it never adds or removes the braces themselves).
      '@stylistic/jsx-curly-brace-presence': 'error',
      // Bare default options (`{ allowAllCaps: false, allowLeadingUnderscore: false, allowNamespace: false }`). Verified directly against the rule's own source (`isDOMComponent`, checked first and unconditionally) that a lowercase-initial tag such as `<myComp />` is never examined at all: JSX itself already reads that as an intrinsic HTML element, not a user component, so this rule only ever runs its own check against a name JSX already treats as a component (one starting with a capital letter, or dotted/namespaced). What it then enforces on that name is genuine PascalCase, catching a stray underscore or other non-alphanumeric character partway through it (`<My_component />`), not the initial letter's own case.
      '@stylistic/jsx-pascal-case': 'error',
      // Bare default options (`{ component: true, html: true }`). Requires `<Foo />` over `<Foo></Foo>` for both a user component and a plain HTML element with no children, a real content/shape choice (not a whitespace/formatting one) Prettier leaves entirely alone.
      '@stylistic/jsx-self-closing-comp': 'error',
    },
  },
];

export default stylisticCommentsConfig;
